server:
  port: 9292
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/customer_info_db
    username: postgres
    password: andreevich27
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
